# Generated by Django 4.2.11 on 2024-04-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="date",
            field=models.CharField(max_length=50),
        ),
    ]
